import React from 'react';
import type { Metadata } from 'next';
import { Inter, Nunito } from 'next/font/google';

import AuthProvider from '@/features/auth/provider/AuthProvider';
import { ModalHost } from '@/features/modal/components/ModalHost';
import { ToastProvider } from '@/shared/ui/Toast';
import { AppHeader } from '@/widgets/app-header/ui';

import './globals.css';

export const metadata: Metadata = {
  title: 'Collab Task Hub',
  description: 'Generated by create next app',
};

const inter = Inter({
  subsets: ['latin', 'cyrillic'],
  variable: '--font-inter',
});

const nunito = Nunito({
  subsets: ['latin', 'cyrillic'],
  variable: '--font-nunito',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${nunito.variable}`}>
      <body>
        <ToastProvider>
          <AppHeader />
          <ModalHost />
          <AuthProvider>
            <div className="container bg-[var(--color-bg-main)]">{children}</div>
          </AuthProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
